#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPoolService.CarPoolDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="carpool")]
	public partial class CarPoolDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_admin(tbl_admin instance);
    partial void Updatetbl_admin(tbl_admin instance);
    partial void Deletetbl_admin(tbl_admin instance);
    partial void Inserttbl_user(tbl_user instance);
    partial void Updatetbl_user(tbl_user instance);
    partial void Deletetbl_user(tbl_user instance);
    partial void Inserttbl_dest(tbl_dest instance);
    partial void Updatetbl_dest(tbl_dest instance);
    partial void Deletetbl_dest(tbl_dest instance);
    partial void Inserttbl_queue(tbl_queue instance);
    partial void Updatetbl_queue(tbl_queue instance);
    partial void Deletetbl_queue(tbl_queue instance);
    partial void Inserttbl_serve(tbl_serve instance);
    partial void Updatetbl_serve(tbl_serve instance);
    partial void Deletetbl_serve(tbl_serve instance);
    partial void Inserttbl_sharelog(tbl_sharelog instance);
    partial void Updatetbl_sharelog(tbl_sharelog instance);
    partial void Deletetbl_sharelog(tbl_sharelog instance);
    partial void Inserttbl_smslog(tbl_smslog instance);
    partial void Updatetbl_smslog(tbl_smslog instance);
    partial void Deletetbl_smslog(tbl_smslog instance);
    partial void Inserttbl_taxistand(tbl_taxistand instance);
    partial void Updatetbl_taxistand(tbl_taxistand instance);
    partial void Deletetbl_taxistand(tbl_taxistand instance);
    #endregion
		
		public CarPoolDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["carpoolConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CarPoolDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarPoolDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarPoolDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarPoolDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_admin> tbl_admins
		{
			get
			{
				return this.GetTable<tbl_admin>();
			}
		}
		
		public System.Data.Linq.Table<tbl_user> tbl_users
		{
			get
			{
				return this.GetTable<tbl_user>();
			}
		}
		
		public System.Data.Linq.Table<tbl_dest> tbl_dests
		{
			get
			{
				return this.GetTable<tbl_dest>();
			}
		}
		
		public System.Data.Linq.Table<tbl_queue> tbl_queues
		{
			get
			{
				return this.GetTable<tbl_queue>();
			}
		}
		
		public System.Data.Linq.Table<tbl_serve> tbl_serves
		{
			get
			{
				return this.GetTable<tbl_serve>();
			}
		}
		
		public System.Data.Linq.Table<tbl_sharelog> tbl_sharelogs
		{
			get
			{
				return this.GetTable<tbl_sharelog>();
			}
		}
		
		public System.Data.Linq.Table<tbl_smslog> tbl_smslogs
		{
			get
			{
				return this.GetTable<tbl_smslog>();
			}
		}
		
		public System.Data.Linq.Table<tbl_taxistand> tbl_taxistands
		{
			get
			{
				return this.GetTable<tbl_taxistand>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_admin")]
	public partial class tbl_admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _name;
		
		private string _password;
		
		private System.Nullable<byte> _remember;
		
		private System.Nullable<byte> _deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnrememberChanging(System.Nullable<byte> value);
    partial void OnrememberChanged();
    partial void OndeletedChanging(System.Nullable<byte> value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remember", DbType="TinyInt")]
		public System.Nullable<byte> remember
		{
			get
			{
				return this._remember;
			}
			set
			{
				if ((this._remember != value))
				{
					this.OnrememberChanging(value);
					this.SendPropertyChanging();
					this._remember = value;
					this.SendPropertyChanged("remember");
					this.OnrememberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt")]
		public System.Nullable<byte> deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_user")]
	public partial class tbl_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _name;
		
		private System.Nullable<byte> _gender;
		
		private System.Nullable<int> _birthyear;
		
		private string _password;
		
		private string _phone_number;
		
		private string _email_address;
		
		private System.Nullable<int> _credits;
		
		private System.Nullable<double> _total_savings;
		
		private System.DateTime _regist_date;
		
		private System.Nullable<byte> _is_grouping;
		
		private System.Nullable<byte> _ind_gender;
		
		private System.Nullable<byte> _grp_gender;
		
		private System.Nullable<byte> _delay_time;
		
		private System.Nullable<System.DateTime> _last_login_date;
		
		private string _image_path;
		
		private System.Nullable<byte> _deleted;
		
		private EntitySet<tbl_queue> _tbl_queues;
		
		private EntitySet<tbl_serve> _tbl_serves;
		
		private EntitySet<tbl_serve> _tbl_serves1;
		
		private EntitySet<tbl_sharelog> _tbl_sharelogs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OngenderChanging(System.Nullable<byte> value);
    partial void OngenderChanged();
    partial void OnbirthyearChanging(System.Nullable<int> value);
    partial void OnbirthyearChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onphone_numberChanging(string value);
    partial void Onphone_numberChanged();
    partial void Onemail_addressChanging(string value);
    partial void Onemail_addressChanged();
    partial void OncreditsChanging(System.Nullable<int> value);
    partial void OncreditsChanged();
    partial void Ontotal_savingsChanging(System.Nullable<double> value);
    partial void Ontotal_savingsChanged();
    partial void Onregist_dateChanging(System.DateTime value);
    partial void Onregist_dateChanged();
    partial void Onis_groupingChanging(System.Nullable<byte> value);
    partial void Onis_groupingChanged();
    partial void Onind_genderChanging(System.Nullable<byte> value);
    partial void Onind_genderChanged();
    partial void Ongrp_genderChanging(System.Nullable<byte> value);
    partial void Ongrp_genderChanged();
    partial void Ondelay_timeChanging(System.Nullable<byte> value);
    partial void Ondelay_timeChanged();
    partial void Onlast_login_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onlast_login_dateChanged();
    partial void Onimage_pathChanging(string value);
    partial void Onimage_pathChanged();
    partial void OndeletedChanging(System.Nullable<byte> value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_user()
		{
			this._tbl_queues = new EntitySet<tbl_queue>(new Action<tbl_queue>(this.attach_tbl_queues), new Action<tbl_queue>(this.detach_tbl_queues));
			this._tbl_serves = new EntitySet<tbl_serve>(new Action<tbl_serve>(this.attach_tbl_serves), new Action<tbl_serve>(this.detach_tbl_serves));
			this._tbl_serves1 = new EntitySet<tbl_serve>(new Action<tbl_serve>(this.attach_tbl_serves1), new Action<tbl_serve>(this.detach_tbl_serves1));
			this._tbl_sharelogs = new EntitySet<tbl_sharelog>(new Action<tbl_sharelog>(this.attach_tbl_sharelogs), new Action<tbl_sharelog>(this.detach_tbl_sharelogs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="TinyInt")]
		public System.Nullable<byte> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthyear", DbType="Int")]
		public System.Nullable<int> birthyear
		{
			get
			{
				return this._birthyear;
			}
			set
			{
				if ((this._birthyear != value))
				{
					this.OnbirthyearChanging(value);
					this.SendPropertyChanging();
					this._birthyear = value;
					this.SendPropertyChanged("birthyear");
					this.OnbirthyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(200)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this.Onphone_numberChanging(value);
					this.SendPropertyChanging();
					this._phone_number = value;
					this.SendPropertyChanged("phone_number");
					this.Onphone_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_address", DbType="NVarChar(200)")]
		public string email_address
		{
			get
			{
				return this._email_address;
			}
			set
			{
				if ((this._email_address != value))
				{
					this.Onemail_addressChanging(value);
					this.SendPropertyChanging();
					this._email_address = value;
					this.SendPropertyChanged("email_address");
					this.Onemail_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_credits", DbType="Int")]
		public System.Nullable<int> credits
		{
			get
			{
				return this._credits;
			}
			set
			{
				if ((this._credits != value))
				{
					this.OncreditsChanging(value);
					this.SendPropertyChanging();
					this._credits = value;
					this.SendPropertyChanged("credits");
					this.OncreditsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_savings", DbType="Float")]
		public System.Nullable<double> total_savings
		{
			get
			{
				return this._total_savings;
			}
			set
			{
				if ((this._total_savings != value))
				{
					this.Ontotal_savingsChanging(value);
					this.SendPropertyChanging();
					this._total_savings = value;
					this.SendPropertyChanged("total_savings");
					this.Ontotal_savingsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regist_date", DbType="SmallDateTime NOT NULL")]
		public System.DateTime regist_date
		{
			get
			{
				return this._regist_date;
			}
			set
			{
				if ((this._regist_date != value))
				{
					this.Onregist_dateChanging(value);
					this.SendPropertyChanging();
					this._regist_date = value;
					this.SendPropertyChanged("regist_date");
					this.Onregist_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_grouping", DbType="TinyInt")]
		public System.Nullable<byte> is_grouping
		{
			get
			{
				return this._is_grouping;
			}
			set
			{
				if ((this._is_grouping != value))
				{
					this.Onis_groupingChanging(value);
					this.SendPropertyChanging();
					this._is_grouping = value;
					this.SendPropertyChanged("is_grouping");
					this.Onis_groupingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ind_gender", DbType="TinyInt")]
		public System.Nullable<byte> ind_gender
		{
			get
			{
				return this._ind_gender;
			}
			set
			{
				if ((this._ind_gender != value))
				{
					this.Onind_genderChanging(value);
					this.SendPropertyChanging();
					this._ind_gender = value;
					this.SendPropertyChanged("ind_gender");
					this.Onind_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grp_gender", DbType="TinyInt")]
		public System.Nullable<byte> grp_gender
		{
			get
			{
				return this._grp_gender;
			}
			set
			{
				if ((this._grp_gender != value))
				{
					this.Ongrp_genderChanging(value);
					this.SendPropertyChanging();
					this._grp_gender = value;
					this.SendPropertyChanged("grp_gender");
					this.Ongrp_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delay_time", DbType="TinyInt")]
		public System.Nullable<byte> delay_time
		{
			get
			{
				return this._delay_time;
			}
			set
			{
				if ((this._delay_time != value))
				{
					this.Ondelay_timeChanging(value);
					this.SendPropertyChanging();
					this._delay_time = value;
					this.SendPropertyChanged("delay_time");
					this.Ondelay_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_login_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> last_login_date
		{
			get
			{
				return this._last_login_date;
			}
			set
			{
				if ((this._last_login_date != value))
				{
					this.Onlast_login_dateChanging(value);
					this.SendPropertyChanging();
					this._last_login_date = value;
					this.SendPropertyChanged("last_login_date");
					this.Onlast_login_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_path", DbType="NVarChar(500)")]
		public string image_path
		{
			get
			{
				return this._image_path;
			}
			set
			{
				if ((this._image_path != value))
				{
					this.Onimage_pathChanging(value);
					this.SendPropertyChanging();
					this._image_path = value;
					this.SendPropertyChanged("image_path");
					this.Onimage_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt")]
		public System.Nullable<byte> deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_tbl_queue", Storage="_tbl_queues", ThisKey="uid", OtherKey="user_id")]
		public EntitySet<tbl_queue> tbl_queues
		{
			get
			{
				return this._tbl_queues;
			}
			set
			{
				this._tbl_queues.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_tbl_serve", Storage="_tbl_serves", ThisKey="uid", OtherKey="user_id")]
		public EntitySet<tbl_serve> tbl_serves
		{
			get
			{
				return this._tbl_serves;
			}
			set
			{
				this._tbl_serves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_tbl_serve1", Storage="_tbl_serves1", ThisKey="uid", OtherKey="user_id2")]
		public EntitySet<tbl_serve> tbl_serves1
		{
			get
			{
				return this._tbl_serves1;
			}
			set
			{
				this._tbl_serves1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_tbl_sharelog", Storage="_tbl_sharelogs", ThisKey="uid", OtherKey="user_id")]
		public EntitySet<tbl_sharelog> tbl_sharelogs
		{
			get
			{
				return this._tbl_sharelogs;
			}
			set
			{
				this._tbl_sharelogs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_queues(tbl_queue entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user = this;
		}
		
		private void detach_tbl_queues(tbl_queue entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user = null;
		}
		
		private void attach_tbl_serves(tbl_serve entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user = this;
		}
		
		private void detach_tbl_serves(tbl_serve entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user = null;
		}
		
		private void attach_tbl_serves1(tbl_serve entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user1 = this;
		}
		
		private void detach_tbl_serves1(tbl_serve entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user1 = null;
		}
		
		private void attach_tbl_sharelogs(tbl_sharelog entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user = this;
		}
		
		private void detach_tbl_sharelogs(tbl_sharelog entity)
		{
			this.SendPropertyChanging();
			entity.tbl_user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_dest")]
	public partial class tbl_dest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _Country;
		
		private string _Lang;
		
		private System.Nullable<long> _ID;
		
		private string _ISO2;
		
		private string _Region1;
		
		private string _Region2;
		
		private string _Region3;
		
		private string _Region4;
		
		private string _ZIP;
		
		private string _City;
		
		private string _Area1;
		
		private string _Area2;
		
		private System.Nullable<decimal> _Lat;
		
		private System.Nullable<decimal> _Lng;
		
		private string _TZ;
		
		private string _UTC;
		
		private string _DST;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnLangChanging(string value);
    partial void OnLangChanged();
    partial void OnIDChanging(System.Nullable<long> value);
    partial void OnIDChanged();
    partial void OnISO2Changing(string value);
    partial void OnISO2Changed();
    partial void OnRegion1Changing(string value);
    partial void OnRegion1Changed();
    partial void OnRegion2Changing(string value);
    partial void OnRegion2Changed();
    partial void OnRegion3Changing(string value);
    partial void OnRegion3Changed();
    partial void OnRegion4Changing(string value);
    partial void OnRegion4Changed();
    partial void OnZIPChanging(string value);
    partial void OnZIPChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnArea1Changing(string value);
    partial void OnArea1Changed();
    partial void OnArea2Changing(string value);
    partial void OnArea2Changed();
    partial void OnLatChanging(System.Nullable<decimal> value);
    partial void OnLatChanged();
    partial void OnLngChanging(System.Nullable<decimal> value);
    partial void OnLngChanged();
    partial void OnTZChanging(string value);
    partial void OnTZChanged();
    partial void OnUTCChanging(string value);
    partial void OnUTCChanged();
    partial void OnDSTChanging(string value);
    partial void OnDSTChanged();
    #endregion
		
		public tbl_dest()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(2)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lang", DbType="NVarChar(2)")]
		public string Lang
		{
			get
			{
				return this._Lang;
			}
			set
			{
				if ((this._Lang != value))
				{
					this.OnLangChanging(value);
					this.SendPropertyChanging();
					this._Lang = value;
					this.SendPropertyChanged("Lang");
					this.OnLangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt")]
		public System.Nullable<long> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISO2", DbType="NVarChar(6)")]
		public string ISO2
		{
			get
			{
				return this._ISO2;
			}
			set
			{
				if ((this._ISO2 != value))
				{
					this.OnISO2Changing(value);
					this.SendPropertyChanging();
					this._ISO2 = value;
					this.SendPropertyChanged("ISO2");
					this.OnISO2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region1", DbType="NVarChar(60)")]
		public string Region1
		{
			get
			{
				return this._Region1;
			}
			set
			{
				if ((this._Region1 != value))
				{
					this.OnRegion1Changing(value);
					this.SendPropertyChanging();
					this._Region1 = value;
					this.SendPropertyChanged("Region1");
					this.OnRegion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region2", DbType="NVarChar(60)")]
		public string Region2
		{
			get
			{
				return this._Region2;
			}
			set
			{
				if ((this._Region2 != value))
				{
					this.OnRegion2Changing(value);
					this.SendPropertyChanging();
					this._Region2 = value;
					this.SendPropertyChanged("Region2");
					this.OnRegion2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region3", DbType="NVarChar(60)")]
		public string Region3
		{
			get
			{
				return this._Region3;
			}
			set
			{
				if ((this._Region3 != value))
				{
					this.OnRegion3Changing(value);
					this.SendPropertyChanging();
					this._Region3 = value;
					this.SendPropertyChanged("Region3");
					this.OnRegion3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region4", DbType="NVarChar(60)")]
		public string Region4
		{
			get
			{
				return this._Region4;
			}
			set
			{
				if ((this._Region4 != value))
				{
					this.OnRegion4Changing(value);
					this.SendPropertyChanging();
					this._Region4 = value;
					this.SendPropertyChanged("Region4");
					this.OnRegion4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIP", DbType="NVarChar(10)")]
		public string ZIP
		{
			get
			{
				return this._ZIP;
			}
			set
			{
				if ((this._ZIP != value))
				{
					this.OnZIPChanging(value);
					this.SendPropertyChanging();
					this._ZIP = value;
					this.SendPropertyChanged("ZIP");
					this.OnZIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(60)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area1", DbType="NVarChar(80)")]
		public string Area1
		{
			get
			{
				return this._Area1;
			}
			set
			{
				if ((this._Area1 != value))
				{
					this.OnArea1Changing(value);
					this.SendPropertyChanging();
					this._Area1 = value;
					this.SendPropertyChanged("Area1");
					this.OnArea1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area2", DbType="NVarChar(80)")]
		public string Area2
		{
			get
			{
				return this._Area2;
			}
			set
			{
				if ((this._Area2 != value))
				{
					this.OnArea2Changing(value);
					this.SendPropertyChanging();
					this._Area2 = value;
					this.SendPropertyChanged("Area2");
					this.OnArea2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this.OnLatChanging(value);
					this.SendPropertyChanging();
					this._Lat = value;
					this.SendPropertyChanged("Lat");
					this.OnLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lng", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> Lng
		{
			get
			{
				return this._Lng;
			}
			set
			{
				if ((this._Lng != value))
				{
					this.OnLngChanging(value);
					this.SendPropertyChanging();
					this._Lng = value;
					this.SendPropertyChanged("Lng");
					this.OnLngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TZ", DbType="NVarChar(30)")]
		public string TZ
		{
			get
			{
				return this._TZ;
			}
			set
			{
				if ((this._TZ != value))
				{
					this.OnTZChanging(value);
					this.SendPropertyChanging();
					this._TZ = value;
					this.SendPropertyChanged("TZ");
					this.OnTZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UTC", DbType="NVarChar(10)")]
		public string UTC
		{
			get
			{
				return this._UTC;
			}
			set
			{
				if ((this._UTC != value))
				{
					this.OnUTCChanging(value);
					this.SendPropertyChanging();
					this._UTC = value;
					this.SendPropertyChanged("UTC");
					this.OnUTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DST", DbType="NVarChar(1)")]
		public string DST
		{
			get
			{
				return this._DST;
			}
			set
			{
				if ((this._DST != value))
				{
					this.OnDSTChanging(value);
					this.SendPropertyChanging();
					this._DST = value;
					this.SendPropertyChanged("DST");
					this.OnDSTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_queue")]
	public partial class tbl_queue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private System.DateTime _enter_time;
		
		private long _user_id;
		
		private System.Nullable<byte> _people_num;
		
		private System.Nullable<byte> _same_gender;
		
		private string _top_color;
		
		private string _other_features;
		
		private long _taxistand_id;
		
		private string _destination;
		
		private decimal _dst_longitude;
		
		private decimal _dst_latitude;
		
		private System.Nullable<int> _group_no;
		
		private System.Nullable<short> _state;
		
		private System.Nullable<System.DateTime> _resp_time;
		
		private System.Nullable<System.DateTime> _queue_time;
		
		private System.Nullable<short> _agree_state;
		
		private System.Nullable<byte> _off_order;
		
		private System.Nullable<decimal> _savingmoney;
		
		private System.Nullable<decimal> _wastetime;
		
		private System.Nullable<System.DateTime> _lastreqtime;
		
		private System.Nullable<System.DateTime> _pairedtime;
		
		private System.Nullable<byte> _deleted;
		
		private System.Nullable<byte> _isnext;
		
		private EntityRef<tbl_user> _tbl_user;
		
		private EntityRef<tbl_taxistand> _tbl_taxistand;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void Onenter_timeChanging(System.DateTime value);
    partial void Onenter_timeChanged();
    partial void Onuser_idChanging(long value);
    partial void Onuser_idChanged();
    partial void Onpeople_numChanging(System.Nullable<byte> value);
    partial void Onpeople_numChanged();
    partial void Onsame_genderChanging(System.Nullable<byte> value);
    partial void Onsame_genderChanged();
    partial void Ontop_colorChanging(string value);
    partial void Ontop_colorChanged();
    partial void Onother_featuresChanging(string value);
    partial void Onother_featuresChanged();
    partial void Ontaxistand_idChanging(long value);
    partial void Ontaxistand_idChanged();
    partial void OndestinationChanging(string value);
    partial void OndestinationChanged();
    partial void Ondst_longitudeChanging(decimal value);
    partial void Ondst_longitudeChanged();
    partial void Ondst_latitudeChanging(decimal value);
    partial void Ondst_latitudeChanged();
    partial void Ongroup_noChanging(System.Nullable<int> value);
    partial void Ongroup_noChanged();
    partial void OnstateChanging(System.Nullable<short> value);
    partial void OnstateChanged();
    partial void Onresp_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onresp_timeChanged();
    partial void Onqueue_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onqueue_timeChanged();
    partial void Onagree_stateChanging(System.Nullable<short> value);
    partial void Onagree_stateChanged();
    partial void Onoff_orderChanging(System.Nullable<byte> value);
    partial void Onoff_orderChanged();
    partial void OnsavingmoneyChanging(System.Nullable<decimal> value);
    partial void OnsavingmoneyChanged();
    partial void OnwastetimeChanging(System.Nullable<decimal> value);
    partial void OnwastetimeChanged();
    partial void OnlastreqtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnlastreqtimeChanged();
    partial void OnpairedtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnpairedtimeChanged();
    partial void OndeletedChanging(System.Nullable<byte> value);
    partial void OndeletedChanged();
    partial void OnisnextChanging(System.Nullable<byte> value);
    partial void OnisnextChanged();
    #endregion
		
		public tbl_queue()
		{
			this._tbl_user = default(EntityRef<tbl_user>);
			this._tbl_taxistand = default(EntityRef<tbl_taxistand>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enter_time", DbType="DateTime NOT NULL")]
		public System.DateTime enter_time
		{
			get
			{
				return this._enter_time;
			}
			set
			{
				if ((this._enter_time != value))
				{
					this.Onenter_timeChanging(value);
					this.SendPropertyChanging();
					this._enter_time = value;
					this.SendPropertyChanged("enter_time");
					this.Onenter_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="BigInt NOT NULL")]
		public long user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._tbl_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_people_num", DbType="TinyInt")]
		public System.Nullable<byte> people_num
		{
			get
			{
				return this._people_num;
			}
			set
			{
				if ((this._people_num != value))
				{
					this.Onpeople_numChanging(value);
					this.SendPropertyChanging();
					this._people_num = value;
					this.SendPropertyChanged("people_num");
					this.Onpeople_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_same_gender", DbType="TinyInt")]
		public System.Nullable<byte> same_gender
		{
			get
			{
				return this._same_gender;
			}
			set
			{
				if ((this._same_gender != value))
				{
					this.Onsame_genderChanging(value);
					this.SendPropertyChanging();
					this._same_gender = value;
					this.SendPropertyChanged("same_gender");
					this.Onsame_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_top_color", DbType="NVarChar(100)")]
		public string top_color
		{
			get
			{
				return this._top_color;
			}
			set
			{
				if ((this._top_color != value))
				{
					this.Ontop_colorChanging(value);
					this.SendPropertyChanging();
					this._top_color = value;
					this.SendPropertyChanged("top_color");
					this.Ontop_colorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_other_features", DbType="NVarChar(255)")]
		public string other_features
		{
			get
			{
				return this._other_features;
			}
			set
			{
				if ((this._other_features != value))
				{
					this.Onother_featuresChanging(value);
					this.SendPropertyChanging();
					this._other_features = value;
					this.SendPropertyChanged("other_features");
					this.Onother_featuresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxistand_id", DbType="BigInt NOT NULL")]
		public long taxistand_id
		{
			get
			{
				return this._taxistand_id;
			}
			set
			{
				if ((this._taxistand_id != value))
				{
					if (this._tbl_taxistand.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontaxistand_idChanging(value);
					this.SendPropertyChanging();
					this._taxistand_id = value;
					this.SendPropertyChanged("taxistand_id");
					this.Ontaxistand_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destination", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string destination
		{
			get
			{
				return this._destination;
			}
			set
			{
				if ((this._destination != value))
				{
					this.OndestinationChanging(value);
					this.SendPropertyChanging();
					this._destination = value;
					this.SendPropertyChanged("destination");
					this.OndestinationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dst_longitude", DbType="Decimal(30,20) NOT NULL")]
		public decimal dst_longitude
		{
			get
			{
				return this._dst_longitude;
			}
			set
			{
				if ((this._dst_longitude != value))
				{
					this.Ondst_longitudeChanging(value);
					this.SendPropertyChanging();
					this._dst_longitude = value;
					this.SendPropertyChanged("dst_longitude");
					this.Ondst_longitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dst_latitude", DbType="Decimal(30,20) NOT NULL")]
		public decimal dst_latitude
		{
			get
			{
				return this._dst_latitude;
			}
			set
			{
				if ((this._dst_latitude != value))
				{
					this.Ondst_latitudeChanging(value);
					this.SendPropertyChanging();
					this._dst_latitude = value;
					this.SendPropertyChanged("dst_latitude");
					this.Ondst_latitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_no", DbType="Int")]
		public System.Nullable<int> group_no
		{
			get
			{
				return this._group_no;
			}
			set
			{
				if ((this._group_no != value))
				{
					this.Ongroup_noChanging(value);
					this.SendPropertyChanging();
					this._group_no = value;
					this.SendPropertyChanged("group_no");
					this.Ongroup_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="SmallInt")]
		public System.Nullable<short> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resp_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> resp_time
		{
			get
			{
				return this._resp_time;
			}
			set
			{
				if ((this._resp_time != value))
				{
					this.Onresp_timeChanging(value);
					this.SendPropertyChanging();
					this._resp_time = value;
					this.SendPropertyChanged("resp_time");
					this.Onresp_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_queue_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> queue_time
		{
			get
			{
				return this._queue_time;
			}
			set
			{
				if ((this._queue_time != value))
				{
					this.Onqueue_timeChanging(value);
					this.SendPropertyChanging();
					this._queue_time = value;
					this.SendPropertyChanged("queue_time");
					this.Onqueue_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agree_state", DbType="SmallInt")]
		public System.Nullable<short> agree_state
		{
			get
			{
				return this._agree_state;
			}
			set
			{
				if ((this._agree_state != value))
				{
					this.Onagree_stateChanging(value);
					this.SendPropertyChanging();
					this._agree_state = value;
					this.SendPropertyChanged("agree_state");
					this.Onagree_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_off_order", DbType="TinyInt")]
		public System.Nullable<byte> off_order
		{
			get
			{
				return this._off_order;
			}
			set
			{
				if ((this._off_order != value))
				{
					this.Onoff_orderChanging(value);
					this.SendPropertyChanging();
					this._off_order = value;
					this.SendPropertyChanged("off_order");
					this.Onoff_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_savingmoney", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> savingmoney
		{
			get
			{
				return this._savingmoney;
			}
			set
			{
				if ((this._savingmoney != value))
				{
					this.OnsavingmoneyChanging(value);
					this.SendPropertyChanging();
					this._savingmoney = value;
					this.SendPropertyChanged("savingmoney");
					this.OnsavingmoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wastetime", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> wastetime
		{
			get
			{
				return this._wastetime;
			}
			set
			{
				if ((this._wastetime != value))
				{
					this.OnwastetimeChanging(value);
					this.SendPropertyChanging();
					this._wastetime = value;
					this.SendPropertyChanged("wastetime");
					this.OnwastetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastreqtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastreqtime
		{
			get
			{
				return this._lastreqtime;
			}
			set
			{
				if ((this._lastreqtime != value))
				{
					this.OnlastreqtimeChanging(value);
					this.SendPropertyChanging();
					this._lastreqtime = value;
					this.SendPropertyChanged("lastreqtime");
					this.OnlastreqtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pairedtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> pairedtime
		{
			get
			{
				return this._pairedtime;
			}
			set
			{
				if ((this._pairedtime != value))
				{
					this.OnpairedtimeChanging(value);
					this.SendPropertyChanging();
					this._pairedtime = value;
					this.SendPropertyChanged("pairedtime");
					this.OnpairedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt")]
		public System.Nullable<byte> deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isnext", DbType="TinyInt")]
		public System.Nullable<byte> isnext
		{
			get
			{
				return this._isnext;
			}
			set
			{
				if ((this._isnext != value))
				{
					this.OnisnextChanging(value);
					this.SendPropertyChanging();
					this._isnext = value;
					this.SendPropertyChanged("isnext");
					this.OnisnextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_tbl_queue", Storage="_tbl_user", ThisKey="user_id", OtherKey="uid", IsForeignKey=true)]
		public tbl_user tbl_user
		{
			get
			{
				return this._tbl_user.Entity;
			}
			set
			{
				tbl_user previousValue = this._tbl_user.Entity;
				if (((previousValue != value) 
							|| (this._tbl_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_user.Entity = null;
						previousValue.tbl_queues.Remove(this);
					}
					this._tbl_user.Entity = value;
					if ((value != null))
					{
						value.tbl_queues.Add(this);
						this._user_id = value.uid;
					}
					else
					{
						this._user_id = default(long);
					}
					this.SendPropertyChanged("tbl_user");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_taxistand_tbl_queue", Storage="_tbl_taxistand", ThisKey="taxistand_id", OtherKey="uid", IsForeignKey=true)]
		public tbl_taxistand tbl_taxistand
		{
			get
			{
				return this._tbl_taxistand.Entity;
			}
			set
			{
				tbl_taxistand previousValue = this._tbl_taxistand.Entity;
				if (((previousValue != value) 
							|| (this._tbl_taxistand.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_taxistand.Entity = null;
						previousValue.tbl_queues.Remove(this);
					}
					this._tbl_taxistand.Entity = value;
					if ((value != null))
					{
						value.tbl_queues.Add(this);
						this._taxistand_id = value.uid;
					}
					else
					{
						this._taxistand_id = default(long);
					}
					this.SendPropertyChanged("tbl_taxistand");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_serve")]
	public partial class tbl_serve : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private long _user_id;
		
		private long _user_id2;
		
		private System.DateTime _serve_date;
		
		private string _start_pos;
		
		private string _end_pos;
		
		private string _end_pos2;
		
		private System.Nullable<double> _saving_money;
		
		private System.Nullable<double> _saving_money2;
		
		private System.Nullable<double> _waste_time;
		
		private System.Nullable<double> _waste_time2;
		
		private System.Nullable<byte> _off_order1;
		
		private System.Nullable<byte> _off_order2;
		
		private System.Nullable<double> _score1;
		
		private System.Nullable<double> _score2;
		
		private EntityRef<tbl_user> _tbl_user;
		
		private EntityRef<tbl_user> _tbl_user1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void Onuser_idChanging(long value);
    partial void Onuser_idChanged();
    partial void Onuser_id2Changing(long value);
    partial void Onuser_id2Changed();
    partial void Onserve_dateChanging(System.DateTime value);
    partial void Onserve_dateChanged();
    partial void Onstart_posChanging(string value);
    partial void Onstart_posChanged();
    partial void Onend_posChanging(string value);
    partial void Onend_posChanged();
    partial void Onend_pos2Changing(string value);
    partial void Onend_pos2Changed();
    partial void Onsaving_moneyChanging(System.Nullable<double> value);
    partial void Onsaving_moneyChanged();
    partial void Onsaving_money2Changing(System.Nullable<double> value);
    partial void Onsaving_money2Changed();
    partial void Onwaste_timeChanging(System.Nullable<double> value);
    partial void Onwaste_timeChanged();
    partial void Onwaste_time2Changing(System.Nullable<double> value);
    partial void Onwaste_time2Changed();
    partial void Onoff_order1Changing(System.Nullable<byte> value);
    partial void Onoff_order1Changed();
    partial void Onoff_order2Changing(System.Nullable<byte> value);
    partial void Onoff_order2Changed();
    partial void Onscore1Changing(System.Nullable<double> value);
    partial void Onscore1Changed();
    partial void Onscore2Changing(System.Nullable<double> value);
    partial void Onscore2Changed();
    #endregion
		
		public tbl_serve()
		{
			this._tbl_user = default(EntityRef<tbl_user>);
			this._tbl_user1 = default(EntityRef<tbl_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="BigInt NOT NULL")]
		public long user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._tbl_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id2", DbType="BigInt NOT NULL")]
		public long user_id2
		{
			get
			{
				return this._user_id2;
			}
			set
			{
				if ((this._user_id2 != value))
				{
					if (this._tbl_user1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_id2Changing(value);
					this.SendPropertyChanging();
					this._user_id2 = value;
					this.SendPropertyChanged("user_id2");
					this.Onuser_id2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serve_date", DbType="DateTime NOT NULL")]
		public System.DateTime serve_date
		{
			get
			{
				return this._serve_date;
			}
			set
			{
				if ((this._serve_date != value))
				{
					this.Onserve_dateChanging(value);
					this.SendPropertyChanging();
					this._serve_date = value;
					this.SendPropertyChanged("serve_date");
					this.Onserve_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_pos", DbType="NVarChar(200)")]
		public string start_pos
		{
			get
			{
				return this._start_pos;
			}
			set
			{
				if ((this._start_pos != value))
				{
					this.Onstart_posChanging(value);
					this.SendPropertyChanging();
					this._start_pos = value;
					this.SendPropertyChanged("start_pos");
					this.Onstart_posChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_pos", DbType="NVarChar(200)")]
		public string end_pos
		{
			get
			{
				return this._end_pos;
			}
			set
			{
				if ((this._end_pos != value))
				{
					this.Onend_posChanging(value);
					this.SendPropertyChanging();
					this._end_pos = value;
					this.SendPropertyChanged("end_pos");
					this.Onend_posChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_pos2", DbType="NVarChar(200)")]
		public string end_pos2
		{
			get
			{
				return this._end_pos2;
			}
			set
			{
				if ((this._end_pos2 != value))
				{
					this.Onend_pos2Changing(value);
					this.SendPropertyChanging();
					this._end_pos2 = value;
					this.SendPropertyChanged("end_pos2");
					this.Onend_pos2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saving_money", DbType="Float")]
		public System.Nullable<double> saving_money
		{
			get
			{
				return this._saving_money;
			}
			set
			{
				if ((this._saving_money != value))
				{
					this.Onsaving_moneyChanging(value);
					this.SendPropertyChanging();
					this._saving_money = value;
					this.SendPropertyChanged("saving_money");
					this.Onsaving_moneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saving_money2", DbType="Float")]
		public System.Nullable<double> saving_money2
		{
			get
			{
				return this._saving_money2;
			}
			set
			{
				if ((this._saving_money2 != value))
				{
					this.Onsaving_money2Changing(value);
					this.SendPropertyChanging();
					this._saving_money2 = value;
					this.SendPropertyChanged("saving_money2");
					this.Onsaving_money2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waste_time", DbType="Float")]
		public System.Nullable<double> waste_time
		{
			get
			{
				return this._waste_time;
			}
			set
			{
				if ((this._waste_time != value))
				{
					this.Onwaste_timeChanging(value);
					this.SendPropertyChanging();
					this._waste_time = value;
					this.SendPropertyChanged("waste_time");
					this.Onwaste_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waste_time2", DbType="Float")]
		public System.Nullable<double> waste_time2
		{
			get
			{
				return this._waste_time2;
			}
			set
			{
				if ((this._waste_time2 != value))
				{
					this.Onwaste_time2Changing(value);
					this.SendPropertyChanging();
					this._waste_time2 = value;
					this.SendPropertyChanged("waste_time2");
					this.Onwaste_time2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_off_order1", DbType="TinyInt")]
		public System.Nullable<byte> off_order1
		{
			get
			{
				return this._off_order1;
			}
			set
			{
				if ((this._off_order1 != value))
				{
					this.Onoff_order1Changing(value);
					this.SendPropertyChanging();
					this._off_order1 = value;
					this.SendPropertyChanged("off_order1");
					this.Onoff_order1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_off_order2", DbType="TinyInt")]
		public System.Nullable<byte> off_order2
		{
			get
			{
				return this._off_order2;
			}
			set
			{
				if ((this._off_order2 != value))
				{
					this.Onoff_order2Changing(value);
					this.SendPropertyChanging();
					this._off_order2 = value;
					this.SendPropertyChanged("off_order2");
					this.Onoff_order2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_score1", DbType="Float")]
		public System.Nullable<double> score1
		{
			get
			{
				return this._score1;
			}
			set
			{
				if ((this._score1 != value))
				{
					this.Onscore1Changing(value);
					this.SendPropertyChanging();
					this._score1 = value;
					this.SendPropertyChanged("score1");
					this.Onscore1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_score2", DbType="Float")]
		public System.Nullable<double> score2
		{
			get
			{
				return this._score2;
			}
			set
			{
				if ((this._score2 != value))
				{
					this.Onscore2Changing(value);
					this.SendPropertyChanging();
					this._score2 = value;
					this.SendPropertyChanged("score2");
					this.Onscore2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_tbl_serve", Storage="_tbl_user", ThisKey="user_id", OtherKey="uid", IsForeignKey=true)]
		public tbl_user tbl_user
		{
			get
			{
				return this._tbl_user.Entity;
			}
			set
			{
				tbl_user previousValue = this._tbl_user.Entity;
				if (((previousValue != value) 
							|| (this._tbl_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_user.Entity = null;
						previousValue.tbl_serves.Remove(this);
					}
					this._tbl_user.Entity = value;
					if ((value != null))
					{
						value.tbl_serves.Add(this);
						this._user_id = value.uid;
					}
					else
					{
						this._user_id = default(long);
					}
					this.SendPropertyChanged("tbl_user");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_tbl_serve1", Storage="_tbl_user1", ThisKey="user_id2", OtherKey="uid", IsForeignKey=true)]
		public tbl_user tbl_user1
		{
			get
			{
				return this._tbl_user1.Entity;
			}
			set
			{
				tbl_user previousValue = this._tbl_user1.Entity;
				if (((previousValue != value) 
							|| (this._tbl_user1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_user1.Entity = null;
						previousValue.tbl_serves1.Remove(this);
					}
					this._tbl_user1.Entity = value;
					if ((value != null))
					{
						value.tbl_serves1.Add(this);
						this._user_id2 = value.uid;
					}
					else
					{
						this._user_id2 = default(long);
					}
					this.SendPropertyChanged("tbl_user1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_sharelog")]
	public partial class tbl_sharelog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private long _user_id;
		
		private System.DateTime _sendtime;
		
		private string _share_content;
		
		private byte _deleted;
		
		private EntityRef<tbl_user> _tbl_user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void Onuser_idChanging(long value);
    partial void Onuser_idChanged();
    partial void OnsendtimeChanging(System.DateTime value);
    partial void OnsendtimeChanged();
    partial void Onshare_contentChanging(string value);
    partial void Onshare_contentChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_sharelog()
		{
			this._tbl_user = default(EntityRef<tbl_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="BigInt NOT NULL")]
		public long user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._tbl_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendtime", DbType="DateTime NOT NULL")]
		public System.DateTime sendtime
		{
			get
			{
				return this._sendtime;
			}
			set
			{
				if ((this._sendtime != value))
				{
					this.OnsendtimeChanging(value);
					this.SendPropertyChanging();
					this._sendtime = value;
					this.SendPropertyChanged("sendtime");
					this.OnsendtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_share_content", DbType="NVarChar(200)")]
		public string share_content
		{
			get
			{
				return this._share_content;
			}
			set
			{
				if ((this._share_content != value))
				{
					this.Onshare_contentChanging(value);
					this.SendPropertyChanging();
					this._share_content = value;
					this.SendPropertyChanged("share_content");
					this.Onshare_contentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_user_tbl_sharelog", Storage="_tbl_user", ThisKey="user_id", OtherKey="uid", IsForeignKey=true)]
		public tbl_user tbl_user
		{
			get
			{
				return this._tbl_user.Entity;
			}
			set
			{
				tbl_user previousValue = this._tbl_user.Entity;
				if (((previousValue != value) 
							|| (this._tbl_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_user.Entity = null;
						previousValue.tbl_sharelogs.Remove(this);
					}
					this._tbl_user.Entity = value;
					if ((value != null))
					{
						value.tbl_sharelogs.Add(this);
						this._user_id = value.uid;
					}
					else
					{
						this._user_id = default(long);
					}
					this.SendPropertyChanged("tbl_user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_smslog")]
	public partial class tbl_smslog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private long _user_id;
		
		private string _receiver;
		
		private byte _valid;
		
		private System.DateTime _sendtime;
		
		private System.Nullable<byte> _deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void Onuser_idChanging(long value);
    partial void Onuser_idChanged();
    partial void OnreceiverChanging(string value);
    partial void OnreceiverChanged();
    partial void OnvalidChanging(byte value);
    partial void OnvalidChanged();
    partial void OnsendtimeChanging(System.DateTime value);
    partial void OnsendtimeChanged();
    partial void OndeletedChanging(System.Nullable<byte> value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_smslog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="BigInt NOT NULL")]
		public long user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receiver", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string receiver
		{
			get
			{
				return this._receiver;
			}
			set
			{
				if ((this._receiver != value))
				{
					this.OnreceiverChanging(value);
					this.SendPropertyChanging();
					this._receiver = value;
					this.SendPropertyChanged("receiver");
					this.OnreceiverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valid", DbType="TinyInt NOT NULL")]
		public byte valid
		{
			get
			{
				return this._valid;
			}
			set
			{
				if ((this._valid != value))
				{
					this.OnvalidChanging(value);
					this.SendPropertyChanging();
					this._valid = value;
					this.SendPropertyChanged("valid");
					this.OnvalidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendtime", DbType="DateTime NOT NULL")]
		public System.DateTime sendtime
		{
			get
			{
				return this._sendtime;
			}
			set
			{
				if ((this._sendtime != value))
				{
					this.OnsendtimeChanging(value);
					this.SendPropertyChanging();
					this._sendtime = value;
					this.SendPropertyChanged("sendtime");
					this.OnsendtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt")]
		public System.Nullable<byte> deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_taxistand")]
	public partial class tbl_taxistand : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _stand_no;
		
		private string _stand_name;
		
		private string _gps_address;
		
		private string _postcode;
		
		private decimal _longitude;
		
		private decimal _latitude;
		
		private string _taxi_stand_type;
		
		private EntitySet<tbl_queue> _tbl_queues;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void Onstand_noChanging(string value);
    partial void Onstand_noChanged();
    partial void Onstand_nameChanging(string value);
    partial void Onstand_nameChanged();
    partial void Ongps_addressChanging(string value);
    partial void Ongps_addressChanged();
    partial void OnpostcodeChanging(string value);
    partial void OnpostcodeChanged();
    partial void OnlongitudeChanging(decimal value);
    partial void OnlongitudeChanged();
    partial void OnlatitudeChanging(decimal value);
    partial void OnlatitudeChanged();
    partial void Ontaxi_stand_typeChanging(string value);
    partial void Ontaxi_stand_typeChanged();
    #endregion
		
		public tbl_taxistand()
		{
			this._tbl_queues = new EntitySet<tbl_queue>(new Action<tbl_queue>(this.attach_tbl_queues), new Action<tbl_queue>(this.detach_tbl_queues));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stand_no", DbType="NVarChar(50)")]
		public string stand_no
		{
			get
			{
				return this._stand_no;
			}
			set
			{
				if ((this._stand_no != value))
				{
					this.Onstand_noChanging(value);
					this.SendPropertyChanging();
					this._stand_no = value;
					this.SendPropertyChanged("stand_no");
					this.Onstand_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stand_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string stand_name
		{
			get
			{
				return this._stand_name;
			}
			set
			{
				if ((this._stand_name != value))
				{
					this.Onstand_nameChanging(value);
					this.SendPropertyChanging();
					this._stand_name = value;
					this.SendPropertyChanged("stand_name");
					this.Onstand_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gps_address", DbType="NVarChar(200)")]
		public string gps_address
		{
			get
			{
				return this._gps_address;
			}
			set
			{
				if ((this._gps_address != value))
				{
					this.Ongps_addressChanging(value);
					this.SendPropertyChanging();
					this._gps_address = value;
					this.SendPropertyChanged("gps_address");
					this.Ongps_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postcode", DbType="NVarChar(15)")]
		public string postcode
		{
			get
			{
				return this._postcode;
			}
			set
			{
				if ((this._postcode != value))
				{
					this.OnpostcodeChanging(value);
					this.SendPropertyChanging();
					this._postcode = value;
					this.SendPropertyChanged("postcode");
					this.OnpostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Decimal(10,6) NOT NULL")]
		public decimal longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="Decimal(10,6) NOT NULL")]
		public decimal latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this.OnlatitudeChanging(value);
					this.SendPropertyChanging();
					this._latitude = value;
					this.SendPropertyChanged("latitude");
					this.OnlatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxi_stand_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string taxi_stand_type
		{
			get
			{
				return this._taxi_stand_type;
			}
			set
			{
				if ((this._taxi_stand_type != value))
				{
					this.Ontaxi_stand_typeChanging(value);
					this.SendPropertyChanging();
					this._taxi_stand_type = value;
					this.SendPropertyChanged("taxi_stand_type");
					this.Ontaxi_stand_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_taxistand_tbl_queue", Storage="_tbl_queues", ThisKey="uid", OtherKey="taxistand_id")]
		public EntitySet<tbl_queue> tbl_queues
		{
			get
			{
				return this._tbl_queues;
			}
			set
			{
				this._tbl_queues.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_queues(tbl_queue entity)
		{
			this.SendPropertyChanging();
			entity.tbl_taxistand = this;
		}
		
		private void detach_tbl_queues(tbl_queue entity)
		{
			this.SendPropertyChanging();
			entity.tbl_taxistand = null;
		}
	}
}
#pragma warning restore 1591
